version: '3'
services:
  mongodb:
    image: mongo:latest

  web:
    image: login:latest
    ports: 
      - 80:80

  api: 
    image: generateuserapi:latest
    ports:
      - 3000:3000
    links:
      - mongodb:mongodb

  # jenkins:
  #   image: jenkinsci/blueocean
  #   ports: 
  #     - 8080:8080
  #   user: root
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock